dictionary/urls.py
from django.urls import path

from .views import Detail, Index

app_name = "dictionary"
urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("dictionaries/<str:source>/<slug:slug>", Detail.as_view(), name="detail"),
]

practice/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dictionary.urls")),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns.insert(0, path("__debug__/", include("debug_toolbar.urls")))

dictionary/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Dictionary(models.Model):
    class SourceLang(models.TextChoices):
        ENGLISH = "en", "en"
        AMERICAN_ENGLISH = "en-us", "en-us"

    slug = models.SlugField(max_length=255)
    word = models.CharField(max_length=255)
    source = models.CharField(
        max_length=50, choices=SourceLang.choices, default=SourceLang.AMERICAN_ENGLISH
    )
    is_headword = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, **kwargs):
        self.word = self.word.lower()
        self.slug = slugify(self.word)
        return super().save(**kwargs)

    def get_absolute_url(self):
        return reverse("dictionary:detail", args=(self.source, self.slug))

dictionary/forms.py
from django import forms

from .models import Dictionary


class DictionaryCreation(forms.ModelForm):
    class Meta:
        model = Dictionary
        fields = ["source", "word"]
        widgets = {
            "word": forms.TextInput(
                attrs={"placeholder": "word", "class": "rounded-r sm:rounded-r-none font-semibold"}
            ),
            "source": forms.Select(attrs={"class": "rounded-l font-semibold"}),
        }

dictionary/views.py
from typing import Any, Dict

from django.db import models
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.text import slugify
from django.views import generic

from .forms import DictionaryCreation
from .models import Dictionary
from .oxford import Entries, Lemmas


class Index(generic.CreateView):
    form_class = DictionaryCreation
    template_name = "dictionary/index.html"

    def post(self, request, **kwargs):

        word = request.POST.get("word", "")
        slug = slugify(word)
        source = request.POST.get("source", "en-us")
        if word and Dictionary.objects.filter(slug=slug, source=source).exists():
            return redirect(reverse("dictionary:detail", args=(source, slug)))

        return super().post(request, **kwargs)

    def get_queryset(self) -> models.query.QuerySet[Dictionary]:
        return Dictionary.objects.all().order_by("-created_at")

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["words"] = self.get_queryset()
        return context


class Detail(generic.DetailView):
    model = Dictionary
    template_name = "dictionary/detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        word = context["object"].word.lower()
        source = context["object"].source.lower()
        oxford_entries = Entries(word, source)
        oxford_entries_result = oxford_entries.result()

        if oxford_entries_result.get("msg"):
            context["oxford_error"] = oxford_entries_result
        elif oxford_entries_result.get("error"):
            context["object"].is_headword = False
            context["object"].save()
            oxford_lemmas = Lemmas(word, source)
            context["oxford_lemmas"] = oxford_lemmas.result()
        else:
            context["oxford_entries"] = oxford_entries_result

        return context

    def get_queryset(self) -> models.query.QuerySet[Dictionary]:
        source = self.kwargs["source"]
        slug = self.kwargs["slug"]
        return Dictionary.objects.filter(source=source, slug=slug)

    def get_object(self) -> Dictionary:
        object = None
        try:
            object = self.get_queryset().get()
        except Dictionary.DoesNotExist:
            word = self.request.GET.get("word")
            source = self.kwargs["source"]
            if bool(int(self.request.GET.get("forceInsert", "0"))) and word:
                object = Dictionary(source=source, word=word)
                object.save()

        if not object:
            raise Http404
        return object

dictionary/templates/dictionary/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
    <a class="hover:text-blue-500" href="{% url 'dictionary:index' %}" title="Home">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
    </a>
    <h1 class="text-2xl font-black text-center">{{ object.word }}</h1>
</div>

<section class="mt-4">
{% if oxford_error %}
    <p class="text-red-500">
        {{ oxford_error.msg }}
    </p>
{% elif oxford_entries %}
    {% include "dictionary/entries.html" with data=oxford_entries %}
{% elif oxford_lemmas %}
    {% include "dictionary/lemmas.html" with data=oxford_lemmas %}
{% endif %}
</section>

{% endblock content %}

dictionary/templates/dictionary/entries.html
{% for result in data.results %}
    {% for lexicalentry in result.lexicalEntries %}
        <section class="mb-2">
            <div class="p-2 font-bold border-b border-black">
                {{ object.word }}
                <span class="lowercase opacity-80 mx-1">({{ lexicalentry.lexicalCategory.id }})</span>
            </div>

            {% for entry in lexicalentry.entries %}

                {% if entry.pronunciations %}
                <div class="p-4">
                    {% for pronunciation in entry.pronunciations %}
                        <span>/{{ pronunciation.phoneticSpelling }}/</span>
                        {% if pronunciation.audioFile %}
                            <audio controls src="{{ pronunciation.audioFile }}"></audio>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endif %}

                {% for sense in entry.senses %}
                <div>
                    <p>{{ sense.definitions.0 }}</p>
                    <ul class="list-disc list-inside">
                        {% for example in sense.examples %}
                            <li>{{ example.text }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endfor %}

            {% endfor %}
        </section>
    {% endfor %}
{% endfor %}

dictionary/templates/dictionary/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-2xl text-center font-black">Dictionaries</h1>

<div class="mt-4">
    <form class="flex flex-wrap justify-center items-center" method="post">
        {% csrf_token %}
        
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div>
            {{ field.errors }}
            {{ field }}
        </div>
        {% endfor %}

        <button class="mt-2 sm:mt-0 btn submit-btn rounded-r" type="submit">Submit</button>
    </form>
</div>

{% if words %}
<section class="mt-4 flex flex-row flex-wrap">
    {% for word in words %}
    <a href="{% url 'dictionary:detail' word.source word.slug %}">
        <span class="word {{ word.is_headword|yesno:"headword,not-headword"}}">
            {{ word.word }} ({{ word.source }})
        </span>
    </a>
    {% endfor %}
</section>
{% endif %}
{% endblock %}

dictionary/templates/dictionary/lemmas.html
{% if data.results %}
    <div class="flex flex-col">
        {% for result in data.results %}
            {% for lexicalentry in result.lexicalEntries %}
                {% for word in lexicalentry.inflectionOf %}
                    <a class="text-blue-500 hover:underline" href="{% url 'dictionary:detail' object.source word.id|slugify %}?forceInsert=1&word={{word.text}}">
                        <span>{{ word.id }} ({{ lexicalentry.lexicalCategory.id }})</span>
                    </a>
                {% endfor %}
            {% endfor %}
        {% endfor %}
    </div>

{% else %}
    <p>No results for <span class="font-bold">{{ object.word }}</span></p>
{% endif %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="flex flex-col h-screen">
    <main class="grow mt-8 mx-6 sm:w-3/4 sm:mx-auto md:w-1/2">
        {% block content %}
        {% endblock content %}
    </main>    
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<hr>
<footer class="mt-4 p-2 flex justify-center items-center flex-col md:flex-row md:justify-around">
    <ul>
        <li>
            <a href="https://github.com/tinnguyentg/django-practice" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                  </svg>
            </a>
        </li>
    </ul>
    <div>
        <img src="https://languages.oup.com/wp-content/uploads/ol-logo-bw-300px-sfw.jpg" alt="OxfordLanguages">
    </div>
</footer>